package sdk.soap;

import sdk.soap.check.CheckRequestObj;
import sdk.soap.check.CheckResponseObj;
import sdk.soap.confirm.ConfirmRequestObj;
import sdk.soap.confirm.ConfirmResponseObj;
import sdk.soap.utils.ObjectFactory;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.7-b01
 * Generated source version: 2.2
 */
@WebService(name = "VerificaVoucher", targetNamespace = "http://bonus.mibact.it/VerificaVoucher/")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
        ObjectFactory.class
})
public interface VerificaVoucher {


    /**
     * @param parameters
     * @return returns CheckResponseObj
     */
    @WebMethod(operationName = "Check", action = "http://bonus.mibact.it/VerificaVoucher/Check")
    @WebResult(name = "CheckResponseObj", targetNamespace = "http://bonus.mibact.it/VerificaVoucher/", partName = "parameters")
    public CheckResponseObj check(
            @WebParam(name = "CheckRequestObj", targetNamespace = "http://bonus.mibact.it/VerificaVoucher/", partName = "parameters")
                    CheckRequestObj parameters);

    /**
     * @param parameters
     * @return returns ConfirmResponseObj
     */
    @WebMethod(operationName = "Confirm", action = "http://bonus.mibact.it/VerificaVoucher/Confirm")
    @WebResult(name = "ConfirmResponseObj", targetNamespace = "http://bonus.mibact.it/VerificaVoucher/", partName = "parameters")
    public ConfirmResponseObj confirm(
            @WebParam(name = "ConfirmRequestObj", targetNamespace = "http://bonus.mibact.it/VerificaVoucher/", partName = "parameters")
                    ConfirmRequestObj parameters);

}
