
package it.mibact.bonus.verificavoucher;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "VerificaVoucher", targetNamespace = "http://bonus.mibact.it/VerificaVoucher/", wsdlLocation = "https://s3.eu-central-1.amazonaws.com/sklivvz-misc/VerificaVoucher.wsdl")
public class VerificaVoucher_Service
    extends Service
{

    private final static URL VERIFICAVOUCHER_WSDL_LOCATION;
    private final static WebServiceException VERIFICAVOUCHER_EXCEPTION;
    private final static QName VERIFICAVOUCHER_QNAME = new QName("http://bonus.mibact.it/VerificaVoucher/", "VerificaVoucher");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("https://s3.eu-central-1.amazonaws.com/sklivvz-misc/VerificaVoucher.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        VERIFICAVOUCHER_WSDL_LOCATION = url;
        VERIFICAVOUCHER_EXCEPTION = e;
    }

    public VerificaVoucher_Service() {
        super(__getWsdlLocation(), VERIFICAVOUCHER_QNAME);
    }

    public VerificaVoucher_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), VERIFICAVOUCHER_QNAME, features);
    }

    public VerificaVoucher_Service(URL wsdlLocation) {
        super(wsdlLocation, VERIFICAVOUCHER_QNAME);
    }

    public VerificaVoucher_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, VERIFICAVOUCHER_QNAME, features);
    }

    public VerificaVoucher_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public VerificaVoucher_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns VerificaVoucher
     */
    @WebEndpoint(name = "VerificaVoucherSOAP")
    public VerificaVoucher getVerificaVoucherSOAP() {
        return super.getPort(new QName("http://bonus.mibact.it/VerificaVoucher/", "VerificaVoucherSOAP"), VerificaVoucher.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns VerificaVoucher
     */
    @WebEndpoint(name = "VerificaVoucherSOAP")
    public VerificaVoucher getVerificaVoucherSOAP(WebServiceFeature... features) {
        return super.getPort(new QName("http://bonus.mibact.it/VerificaVoucher/", "VerificaVoucherSOAP"), VerificaVoucher.class, features);
    }

    private static URL __getWsdlLocation() {
        if (VERIFICAVOUCHER_EXCEPTION!= null) {
            throw VERIFICAVOUCHER_EXCEPTION;
        }
        return VERIFICAVOUCHER_WSDL_LOCATION;
    }

}
